version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: postgresRag
      POSTGRES_USER: postgresRag
      POSTGRES_PASSWORD: postgresRag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_rag:/var/lib/postgresql/data

volumes:
  postgres_data_rag:

