spring:
  application:
    name: spring-ai-2-substack-hero
  ai:
    ollama:
      chat:
        options:
          model: "qwen3"
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG